# -*- coding: utf-8 -*-
"""hierarchical_model_hpc

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WBoShhu69cQmm_UAD6KaiUZ7kZsMaKOd
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import AgglomerativeClustering
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score
from scipy.cluster.hierarchy import linkage, dendrogram

# -------------------------
# 1. LOAD DATA
# -------------------------
orders = pd.read_csv("orders.csv")
order_products_prior = pd.read_csv("order_products__prior.csv")

print("Orders shape:", orders.shape)
print("Prior order products shape:", order_products_prior.shape)

# -------------------------
# 2. MERGE DATA
# -------------------------
data = order_products_prior.merge(
    orders[["order_id", "user_id", "order_number", "order_hour_of_day", "days_since_prior_order"]],
    on="order_id",
    how="left"
)

print("Merged data shape:", data.shape)

# -------------------------
# 3. CREATE CUSTOMER FEATURES
# -------------------------
customer_features = orders.groupby("user_id").agg(
    total_orders=("order_number", "max"),
    avg_days_between_orders=("days_since_prior_order", "mean"),
    avg_order_hour=("order_hour_of_day", "mean")
).reset_index()

order_variability = orders.groupby("user_id")["order_number"].var().reset_index()
order_variability.columns = ["user_id", "order_variability"]
customer_features = customer_features.merge(order_variability, on="user_id", how="left")

basket_size = data.groupby(["user_id", "order_id"]).size().reset_index(name="basket_size")
avg_basket_size = basket_size.groupby("user_id")["basket_size"].mean().reset_index()
avg_basket_size.columns = ["user_id", "avg_basket_size"]
customer_features = customer_features.merge(avg_basket_size, on="user_id", how="left")

reorder_rate = data.groupby("user_id")["reordered"].mean().reset_index()
reorder_rate.columns = ["user_id", "reorder_rate"]
customer_features = customer_features.merge(reorder_rate, on="user_id", how="left")

customer_features = customer_features.fillna(0)

print("\nCustomer feature sample:")
print(customer_features.head())

# -------------------------
# 4. TRANSFORM SKEWED FEATURES
# -------------------------
customer_features["total_orders"] = np.log1p(customer_features["total_orders"])
customer_features["avg_basket_size"] = np.log1p(customer_features["avg_basket_size"])

# -------------------------
# 5. SELECT FEATURES
# -------------------------
feature_cols = [
    "total_orders",
    "avg_days_between_orders",
    "avg_order_hour",
    "order_variability",
    "avg_basket_size",
    "reorder_rate"
]

features = customer_features[feature_cols]

# -------------------------
# 6. SCALE FEATURES
# -------------------------
scaler = StandardScaler()
scaled_features = scaler.fit_transform(features)

print("\nScaled feature matrix shape:", scaled_features.shape)

# -------------------------
# 7. DENDROGRAM ON SAMPLE ONLY
# -------------------------
dendro_size = 1000
np.random.seed(42)

dendro_idx = np.random.choice(
    len(scaled_features),
    size=min(dendro_size, len(scaled_features)),
    replace=False
)
dendro_data = scaled_features[dendro_idx]

linked = linkage(dendro_data, method="ward")

plt.figure(figsize=(12, 6))
dendrogram(linked, truncate_mode="lastp", p=30)
plt.title("Hierarchical Clustering Dendrogram (Sampled)")
plt.xlabel("Cluster Groups")
plt.ylabel("Distance")
plt.tight_layout()
plt.savefig("hierarchical_dendrogram.png", dpi=200)
plt.close()

print("Saved: hierarchical_dendrogram.png")

# -------------------------
# 8. HIERARCHICAL CLUSTERING ON FULL DATA
# -------------------------
n_clusters = 4

hierarchical = AgglomerativeClustering(
    n_clusters=n_clusters,
    linkage="ward"
)

customer_features["hierarchical_cluster"] = hierarchical.fit_predict(scaled_features)

print("\nHierarchical clustering completed.")
print(customer_features[["user_id", "hierarchical_cluster"]].head())

# -------------------------
# 9. SILHOUETTE SCORE
# -------------------------
sample_n = min(10000, len(customer_features))

score = silhouette_score(
    scaled_features,
    customer_features["hierarchical_cluster"],
    sample_size=sample_n,
    random_state=42
)

print(f"\nSilhouette Score: {score:.4f}")

# -------------------------
# 10. PCA VISUALIZATION
# -------------------------
pca = PCA(n_components=2, random_state=42)
pca_features = pca.fit_transform(scaled_features)

plt.figure(figsize=(8, 6))
plt.scatter(
    pca_features[:, 0],
    pca_features[:, 1],
    c=customer_features["hierarchical_cluster"],
    s=10
)
plt.title("Hierarchical Clustering on Full Customer Dataset")
plt.xlabel("PCA 1")
plt.ylabel("PCA 2")
plt.grid(True)
plt.tight_layout()
plt.savefig("hierarchical_pca_plot.png", dpi=200)
plt.close()

print("Saved: hierarchical_pca_plot.png")

# -------------------------
# 11. CLUSTER PROFILE
# -------------------------
cluster_profile = customer_features.drop(columns=["user_id"]).groupby("hierarchical_cluster").mean()

print("\nCluster Profile:")
print(cluster_profile)

# -------------------------
# 12. CLUSTER COUNTS
# -------------------------
cluster_counts = customer_features["hierarchical_cluster"].value_counts().sort_index()

print("\nCluster Counts:")
print(cluster_counts)

# -------------------------
# 13. SAVE RESULTS
# -------------------------
customer_features.to_csv("customer_segmentation_hierarchical_results.csv", index=False)
cluster_profile.to_csv("customer_segmentation_hierarchical_cluster_profile.csv")
cluster_counts.to_csv("customer_segmentation_hierarchical_cluster_counts.csv", header=["count"])

print("\nFiles saved:")
print("- customer_segmentation_hierarchical_results.csv")
print("- customer_segmentation_hierarchical_cluster_profile.csv")
print("- customer_segmentation_hierarchical_cluster_counts.csv")
print("- hierarchical_dendrogram.png")
print("- hierarchical_pca_plot.png")

"""# =========================
# FINAL RESULT - HIERARCHICAL CLUSTERING
# =========================



Hierarchical Clustering was successfully applied to the full customer-level dataset using HPC resources.

The model identified 4 distinct customer clusters based on purchasing behavior. The PCA visualization shows clear separation between clusters, indicating effective segmentation.

A dendrogram was generated using a representative subset of the data to visualize how clusters are formed and merged step by step. Due to computational complexity, full dataset dendrogram visualization was not feasible.

The resulting clusters are meaningful and align well with behavioral patterns such as moderate shoppers, low-engagement users, loyal customers, and high-value users.

Overall, Hierarchical Clustering provided strong interpretability and confirmed the structure of customer segments observed in other models.

"""