# -*- coding: utf-8 -*-
"""gmm_model_hpc

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PmraZSj3DjZCuT6zvksWJodl8WmYtDZt
"""

# =========================================================
# GMM - FULL DATASET
# INSTACART CUSTOMER SEGMENTATION
# =========================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score
from sklearn.mixture import GaussianMixture

# -------------------------
# 1. LOAD DATA
# -------------------------
orders = pd.read_csv("orders.csv")
order_products_prior = pd.read_csv("order_products__prior.csv")

print("Orders shape:", orders.shape)
print("Prior order products shape:", order_products_prior.shape)

# -------------------------
# 2. MERGE DATA
# -------------------------
data = order_products_prior.merge(
    orders[["order_id", "user_id", "order_number", "order_hour_of_day", "days_since_prior_order"]],
    on="order_id",
    how="left"
)

print("Merged data shape:", data.shape)

# -------------------------
# 3. CREATE CUSTOMER FEATURES
# -------------------------
customer_features = orders.groupby("user_id").agg(
    total_orders=("order_number", "max"),
    avg_days_between_orders=("days_since_prior_order", "mean"),
    avg_order_hour=("order_hour_of_day", "mean")
).reset_index()

# Order variability
order_variability = orders.groupby("user_id")["order_number"].var().reset_index()
order_variability.columns = ["user_id", "order_variability"]
customer_features = customer_features.merge(order_variability, on="user_id", how="left")

# Average basket size
basket_size = data.groupby(["user_id", "order_id"]).size().reset_index(name="basket_size")
avg_basket_size = basket_size.groupby("user_id")["basket_size"].mean().reset_index()
avg_basket_size.columns = ["user_id", "avg_basket_size"]
customer_features = customer_features.merge(avg_basket_size, on="user_id", how="left")

# Reorder rate
reorder_rate = data.groupby("user_id")["reordered"].mean().reset_index()
reorder_rate.columns = ["user_id", "reorder_rate"]
customer_features = customer_features.merge(reorder_rate, on="user_id", how="left")

customer_features = customer_features.fillna(0)

print("\nCustomer feature sample:")
print(customer_features.head())

# -------------------------
# 4. LOG TRANSFORM
# -------------------------
customer_features["total_orders"] = np.log1p(customer_features["total_orders"])
customer_features["avg_basket_size"] = np.log1p(customer_features["avg_basket_size"])

# -------------------------
# 5. SELECT FEATURES
# -------------------------
feature_cols = [
    "total_orders",
    "avg_days_between_orders",
    "avg_order_hour",
    "order_variability",
    "avg_basket_size",
    "reorder_rate"
]

features = customer_features[feature_cols]

# -------------------------
# 6. SCALE FEATURES
# -------------------------
scaler = StandardScaler()
scaled_features = scaler.fit_transform(features)

print("\nScaled feature matrix shape:", scaled_features.shape)

# -------------------------
# 7. APPLY GMM ON FULL DATA
# -------------------------
n_clusters = 4

gmm = GaussianMixture(
    n_components=n_clusters,
    covariance_type="full",
    random_state=42
)

customer_features["gmm_cluster"] = gmm.fit_predict(scaled_features)

# Optional: soft cluster probabilities
gmm_probabilities = gmm.predict_proba(scaled_features)

for i in range(n_clusters):
    customer_features[f"gmm_prob_cluster_{i}"] = gmm_probabilities[:, i]

print("\nGMM clustering completed.")
print(customer_features[["user_id", "gmm_cluster"]].head())

# -------------------------
# 8. SILHOUETTE SCORE
# -------------------------
sample_n = min(10000, len(customer_features))

score = silhouette_score(
    scaled_features,
    customer_features["gmm_cluster"],
    sample_size=sample_n,
    random_state=42
)

print(f"\nSilhouette Score: {score:.4f}")

# -------------------------
# 9. CLUSTER COUNTS
# -------------------------
cluster_counts = customer_features["gmm_cluster"].value_counts().sort_index()

print("\nCluster Counts:")
print(cluster_counts)

# -------------------------
# 10. CLUSTER PROFILE
# -------------------------
cluster_profile = customer_features.drop(columns=["user_id"] + [f"gmm_prob_cluster_{i}" for i in range(n_clusters)]).groupby("gmm_cluster").mean()

print("\nCluster Profile:")
print(cluster_profile)

# -------------------------
# 11. PCA VISUALIZATION
# -------------------------
pca = PCA(n_components=2, random_state=42)
pca_features = pca.fit_transform(scaled_features)

plt.figure(figsize=(8, 6))
plt.scatter(
    pca_features[:, 0],
    pca_features[:, 1],
    c=customer_features["gmm_cluster"],
    s=10
)
plt.title("GMM Clustering on Full Customer Dataset")
plt.xlabel("PCA 1")
plt.ylabel("PCA 2")
plt.grid(True)
plt.tight_layout()
plt.savefig("gmm_pca_plot.png", dpi=200)
plt.close()

print("Saved: gmm_pca_plot.png")

# -------------------------
# 12. MODEL METRICS
# -------------------------
print("\nGMM Model Metrics:")
print("AIC:", gmm.aic(scaled_features))
print("BIC:", gmm.bic(scaled_features))

# -------------------------
# 13. SAVE RESULTS
# -------------------------
customer_features.to_csv("customer_segmentation_gmm_results.csv", index=False)
cluster_profile.to_csv("customer_segmentation_gmm_cluster_profile.csv")
cluster_counts.to_csv("customer_segmentation_gmm_cluster_counts.csv", header=["count"])

print("\nFiles saved:")
print("- customer_segmentation_gmm_results.csv")
print("- customer_segmentation_gmm_cluster_profile.csv")
print("- customer_segmentation_gmm_cluster_counts.csv")
print("- gmm_pca_plot.png")

"""# =========================
# FINAL RESULT - GMM
# =========================


The Gaussian Mixture Model (GMM) was successfully applied to the full customer-level dataset to perform segmentation based on purchasing behavior.

The model identified 4 distinct customer clusters, similar to K-Means and Hierarchical Clustering, but with smoother boundaries between groups.

Unlike hard clustering methods, GMM assigns probabilities to each cluster, allowing customers to belong partially to multiple segments. This provides a more realistic representation of real-world behavior.

The PCA visualization shows well-distributed clusters with gradual transitions, indicating that customer behavior is continuous rather than sharply separated.

The silhouette score indicates moderate cluster separation, which is expected for large-scale behavioral data where overlap between groups is natural.

Overall, GMM provided flexible and meaningful segmentation, making it one of the most effective models for this dataset.

"""