# -*- coding: utf-8 -*-
"""dbscan_model_hpc

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15PRFfn0U4PxOcdbajrRXWGzGbWlxhSUk
"""

# =========================================================
# DBSCAN - FULL DATASET
# INSTACART CUSTOMER SEGMENTATION
# =========================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import DBSCAN
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

# -------------------------
# 1. LOAD DATA
# -------------------------
orders = pd.read_csv("orders.csv")
order_products_prior = pd.read_csv("order_products__prior.csv")

print("Orders shape:", orders.shape)
print("Prior order products shape:", order_products_prior.shape)

# -------------------------
# 2. MERGE DATA
# -------------------------
data = order_products_prior.merge(
    orders[["order_id", "user_id", "order_number", "order_hour_of_day", "days_since_prior_order"]],
    on="order_id",
    how="left"
)

print("Merged data shape:", data.shape)

# -------------------------
# 3. CREATE CUSTOMER FEATURES
# -------------------------
customer_features = orders.groupby("user_id").agg(
    total_orders=("order_number", "max"),
    avg_days_between_orders=("days_since_prior_order", "mean"),
    avg_order_hour=("order_hour_of_day", "mean")
).reset_index()

# Order variability
order_variability = orders.groupby("user_id")["order_number"].var().reset_index()
order_variability.columns = ["user_id", "order_variability"]
customer_features = customer_features.merge(order_variability, on="user_id", how="left")

# Average basket size
basket_size = data.groupby(["user_id", "order_id"]).size().reset_index(name="basket_size")
avg_basket_size = basket_size.groupby("user_id")["basket_size"].mean().reset_index()
avg_basket_size.columns = ["user_id", "avg_basket_size"]
customer_features = customer_features.merge(avg_basket_size, on="user_id", how="left")

# Reorder rate
reorder_rate = data.groupby("user_id")["reordered"].mean().reset_index()
reorder_rate.columns = ["user_id", "reorder_rate"]
customer_features = customer_features.merge(reorder_rate, on="user_id", how="left")

customer_features = customer_features.fillna(0)

print("\nCustomer feature sample:")
print(customer_features.head())

# -------------------------
# 4. LOG TRANSFORM
# -------------------------
customer_features["total_orders"] = np.log1p(customer_features["total_orders"])
customer_features["avg_basket_size"] = np.log1p(customer_features["avg_basket_size"])

# -------------------------
# 5. SELECT FEATURES
# -------------------------
feature_cols = [
    "total_orders",
    "avg_days_between_orders",
    "avg_order_hour",
    "order_variability",
    "avg_basket_size",
    "reorder_rate"
]

features = customer_features[feature_cols]

# -------------------------
# 6. SCALE FEATURES
# -------------------------
scaler = StandardScaler()
scaled_features = scaler.fit_transform(features)

print("\nScaled feature matrix shape:", scaled_features.shape)

# -------------------------
# 7. APPLY DBSCAN ON FULL DATA
# -------------------------
# Tune these on HPC if needed
eps_value = 0.8
min_samples_value = 10

dbscan = DBSCAN(
    eps=eps_value,
    min_samples=min_samples_value,
    n_jobs=-1
)

customer_features["dbscan_cluster"] = dbscan.fit_predict(scaled_features)

print("\nDBSCAN clustering completed.")
print(customer_features[["user_id", "dbscan_cluster"]].head())

# -------------------------
# 8. CLUSTER COUNTS
# -------------------------
cluster_counts = customer_features["dbscan_cluster"].value_counts().sort_index()

print("\nCluster Counts:")
print(cluster_counts)

# -------------------------
# 9. NUMBER OF CLUSTERS / NOISE
# -------------------------
n_clusters = len(set(customer_features["dbscan_cluster"])) - (
    1 if -1 in customer_features["dbscan_cluster"].values else 0
)

n_noise = (customer_features["dbscan_cluster"] == -1).sum()

print(f"\nEstimated number of clusters: {n_clusters}")
print(f"Number of noise points: {n_noise}")

# -------------------------
# 10. SILHOUETTE SCORE
# -------------------------
clustered_only = customer_features[customer_features["dbscan_cluster"] != -1].copy()

if clustered_only["dbscan_cluster"].nunique() > 1:
    clustered_scaled = scaled_features[customer_features["dbscan_cluster"] != -1]

    sample_n = min(10000, len(clustered_only))

    score = silhouette_score(
        clustered_scaled,
        clustered_only["dbscan_cluster"],
        sample_size=sample_n,
        random_state=42
    )
    print(f"Silhouette Score (excluding noise): {score:.4f}")
else:
    print("Silhouette Score cannot be computed because DBSCAN found fewer than 2 clusters.")

# -------------------------
# 11. PCA VISUALIZATION
# -------------------------
pca = PCA(n_components=2, random_state=42)
pca_features = pca.fit_transform(scaled_features)

plt.figure(figsize=(8, 6))
scatter = plt.scatter(
    pca_features[:, 0],
    pca_features[:, 1],
    c=customer_features["dbscan_cluster"],
    s=10
)
plt.title("DBSCAN Clustering on Full Customer Dataset")
plt.xlabel("PCA 1")
plt.ylabel("PCA 2")
plt.grid(True)
plt.tight_layout()
plt.savefig("dbscan_pca_plot.png", dpi=200)
plt.close()

print("Saved: dbscan_pca_plot.png")

# -------------------------
# 12. CLUSTER PROFILE
# -------------------------
if not clustered_only.empty and clustered_only["dbscan_cluster"].nunique() > 0:
    cluster_profile = clustered_only.groupby("dbscan_cluster")[feature_cols].mean()

    print("\nCluster Profile:")
    print(cluster_profile)
else:
    cluster_profile = pd.DataFrame()
    print("\nNo valid clusters found for profiling.")

# -------------------------
# 13. SAVE RESULTS
# -------------------------
customer_features.to_csv("customer_segmentation_dbscan_results.csv", index=False)

if not cluster_profile.empty:
    cluster_profile.to_csv("customer_segmentation_dbscan_cluster_profile.csv")

cluster_counts.to_csv("customer_segmentation_dbscan_cluster_counts.csv", header=["count"])

print("\nFiles saved:")
print("- customer_segmentation_dbscan_results.csv")
if not cluster_profile.empty:
    print("- customer_segmentation_dbscan_cluster_profile.csv")
print("- customer_segmentation_dbscan_cluster_counts.csv")
print("- dbscan_pca_plot.png")

"""# =========================
# FINAL RESULT - DBSCAN
# =========================



DBSCAN was applied to the full customer-level dataset to identify clusters based on density and detect outliers.

The model resulted in one dominant cluster containing the majority of customers, along with a small number of noise points (outliers). This indicates that the dataset does not have clearly separable density-based clusters.

The PCA visualization confirms that most data points belong to a single group, showing that customer behavior is continuous rather than forming distinct dense regions.

As a result, DBSCAN was not effective for segmentation in this dataset, but it was useful for identifying outliers.

Overall, this highlights that density-based clustering is not suitable for this type of customer behavior data.

"""